status: true
dependencies:
  module:
    - lupus_decoupled_site_info
    - serialization
    - user
id: lupus_decoupled_site_info
plugin_id: lupus_decoupled_site_info
granularity: resource
configuration:
  methods:
    - GET
  formats:
    - json
  authentication:
    - cookie
