import { defineEventHandler, readBody, createError, getHeader } from 'h3'
import { createKbPage } from '../../utils/drupal'
import { resolveSpaceId } from '../../utils/spaces'
import { storedBody } from '../../utils/title-heading'

/**
 * POST /api/kb  { title, space }  →  { nid, uuid, title, path }
 *
 * In-app page creation. `space` is the space the CTA was invoked from — a term
 * UUID, or the URL slug the sidebar and landing page link with.
 * It is context, not a form field (OKB-63): the caller states which space it is
 * creating in, and the server never guesses one.
 *
 * The page lands as a **draft** (OKB-64) whose seed body is the title
 * heading a write spells, block id and all — so the page is citable from the
 * moment it exists. Its `<space-slug>/<title>` alias is generated by pathauto,
 * and the client navigates to the returned `path` with `?edit` — so the
 * author's next interaction is the in-place editor on their own new page, not
 * a form.
 *
 * Errors are Drupal's: no create access is a 403, a violated field constraint is
 * a 422 whose per-field violations ride along in `data.violations` (upstream.ts)
 * for the dialog to render.
 */
export default defineEventHandler(async (event) => {
  if (!getHeader(event, 'cookie')) {
    throw createError({ statusCode: 401, statusMessage: 'Authentication required — log in via /user/login' })
  }

  const body = await readBody<{ title?: unknown, space?: unknown }>(event)
  const title = typeof body?.title === 'string' ? body.title.trim() : ''
  const space = typeof body?.space === 'string' ? body.space.trim() : ''
  if (!title) {
    throw createError({ statusCode: 400, statusMessage: 'A title is required' })
  }
  if (!space) {
    throw createError({ statusCode: 400, statusMessage: 'A space is required' })
  }

  return createKbPage(event, {
    title,
    spaceId: await resolveSpaceId(event, space),
    // The title heading a write spells, block id and all: it is the lead
    // section's anchor (server/utils/title-heading.ts).
    body: storedBody('', title, ''),
  })
})
