inline_comment.settings:
  type: config_object
  label: 'Inline comment settings'
  mapping:
    entity_types:
      type: sequence
      label: 'Commentable entity types'
      sequence:
        type: string
        label: 'Entity type ID'
